import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.patches as mpatches
from matplotlib.patches import ConnectionPatch, FancyArrowPatch
import numpy as np
import pandas as pd

def waterMark(k:str)->str:
    """Returns a descriptive title for a given variable key."""
    titles = {'H': 'Cum. Health', 'N': 'Cum. Need', 'T': 'Cum Treatment', 'E': 'Cum Expectation', 'C': 'Cum Contacts',
              'O': 'Cum Noise-exp', 'D':'Cum Disease',
              'h': 'Inst. Health', 't':'Inst. Treatment', 'b': 'Inst. % seeking', 'e': 'Inst. Expectation',
              'o': 'Inst. noise-exp', 'd': 'Inst. disease', 'c': 'Inst. % seeking got appointment'}
    return titles.get(k, k) # Return the key itself if not found

def proportionC(data: pd.DataFrame, low_h_cut: float, high_h_cut:float) -> pd.Series:
    """Compute the proportion of patients who got appointment from the total asking for appointments."""
    C = data['SimpleC'].loc[(data['H']['100'] <= high_h_cut) & (data['H']['100'] >= low_h_cut)]
    B = data['SimpleB'].loc[(data['H']['100'] <= high_h_cut) & (data['H']['100'] >= low_h_cut)]
    return C.mask(cond=B!=1)

def onePlot(ax: mpl.axes.Axes,dd: pd.DataFrame, plotVariable: str, color: str, low_h_cut: float = None, high_h_cut:float = None,
            plotData:pd.DataFrame = None) -> mpl.axes.Axes:
    """Plots a single data trajectory onto a given axis."""
    #ExtractPlotData
    if plotData is None:
        plotData = dd[plotVariable.strip('_diff').strip('_cum')].loc[(dd['H']['100'] <= high_h_cut) & (dd['H']['100'] >= low_h_cut )] \
        if plotVariable not in ['c'] else proportionC(data=dd, low_h_cut=low_h_cut, high_h_cut=high_h_cut)
    #Comput diff or cum if needed
    plotData = plotData.diff(axis=1) if '_diff' in plotVariable else plotData
    plotData = plotData.cumsum(axis=1) if '_cum' in plotVariable else plotData
    ax.plot([x for x in range(plotData.shape[1])], plotData.mean(), color=color, linewidth=3)
    ax.set_xlabel(plotVariable, fontsize = 20)
    return ax

def complexAxeDict() -> dict:
    """Creates and returns the complex mosaic of axes for the plot."""
    axd = plt.figure(layout="constrained", figsize = (30,30)).subplot_mosaic(
    """
    sssss
    HhddD
    1pp..
    NpptT
    73333
    7blcC
    7999.
    EexoO
    """,
    gridspec_kw=dict(width_ratios=[1,1,0.5,1,1], height_ratios=[0.1,1,0.2,1,0.2,1,0.2,1])
    )
    return axd

def populate_axe(ax_dict: dict, dd: pd.DataFrame, low_h_cut: float = None, high_h_cut:float = None, sub_title:str = "", filteredData:pd.DataFrame = None):
    """
    Populates the complex axes layout with data plots and explanatory arrows.

    Parameters
    ----------
    ax_dict : dict[str, mpl.axes.Axes]
        A dictionary mapping keys to Axes objects, as generated by subplot_mosaic.
    dd : pd.DataFrame
        The DataFrame containing the simulation data.
    low_h_cut, high_h_cut : float, optional
        The health value thresholds for filtering the data.
    sub_title : str, optional
        A subtitle to be displayed.
    filteredData : pd.DataFrame, optional
        Pre-filtered data to be plotted.
    """
    cmap = mpl.colormaps['plasma']
    arrow_color = cmap(0.8)
    scale = 25
    lineScale = scale / 4.5
    text_size = 40
    waterSize = 25
    subtitleSize = 25

    # --- Draw static arrows and text ---
    static_elements = {
        '1': [mpatches.FancyArrowPatch(posA=(0.5, 1), posB=(0.5, 0), mutation_scale=scale, color=arrow_color)],
        '3': [
            ConnectionPatch(xyA=(0, 0.6), xyB=(0.0, 0.3), coordsA='data', lw=lineScale, color=arrow_color),
            ConnectionPatch(xyA=(0.0, 0.3), xyB=(0.6, 0.3), coordsA='data', lw=lineScale, color=arrow_color),
            ConnectionPatch(xyA=(0.85, 0), xyB=(0.85, 0.3), coordsA='data', lw=lineScale, color=arrow_color),
            ConnectionPatch(xyA=(0.85, 0.3), xyB=(0.6, 0.3), coordsA='data', lw=lineScale, color=arrow_color),
            mpatches.FancyArrowPatch(posA=(0.6, 0.3), posB=(0.6, 1), mutation_scale=scale, color=arrow_color)
        ],
        '7': [
            ConnectionPatch(xyA=(0.2, 1), xyB=(0.2, 0.5), coordsA='data', lw=lineScale, color=arrow_color),
            ConnectionPatch(xyA=(0.2, 0), xyB=(0.2, 0.5), coordsA='data', lw=lineScale, color=arrow_color),
            mpatches.FancyArrowPatch(posA=(0.2, 0.5), posB=(1, 0.5), mutation_scale=scale, color=arrow_color)
        ],
        'p': [
            ConnectionPatch(xyA=(1, 0.5), xyB=(0.25, 0.5), coordsA='data', lw=lineScale, color=arrow_color),
            ConnectionPatch(xyA=(0.85, 0.9), xyB=(0.85, 0.5), coordsA='data', lw=lineScale, color=arrow_color),
            mpatches.FancyArrowPatch(posA=(0.25, 0.5), posB=(0.25, 1), hatch='o', mutation_scale=scale, color=arrow_color)
        ],
        'l': [mpatches.FancyArrowPatch(posA=(0, 0.5), posB=(1, 0.5), hatch='o', mutation_scale=scale, color=arrow_color)],
        '9': [
            ConnectionPatch(xyA=(0.86, 0.9), xyB=(0.86, 0.5), coordsA='data', lw=lineScale, color=arrow_color),
            ConnectionPatch(xyA=(0.86, 0.5), xyB=(0.2, 0.5), coordsA='data', lw=lineScale, color=arrow_color),
            ConnectionPatch(xyA=(0.76, 0.1), xyB=(0.76, 0.5), coordsA='data', lw=lineScale, color=arrow_color),
            ConnectionPatch(xyA=(0.3, 0.9), xyB=(0.3, 0.5), coordsA='data', lw=lineScale, color=arrow_color),
            mpatches.FancyArrowPatch(posA=(0.2, 0.5), posB=(0.2, 0), hatch='o', mutation_scale=scale, color=arrow_color)
        ]
    }
    text_elements = {
        '3': (0.3, 0.6, "Prescription", text_size),
        '7': (0.6, 0.6, "Behaviour", text_size),
        'p': (0.5, 0.3, "Progression", text_size),
        'l': (0.4, 0.8, "Allocation", text_size),
        'x': (0.5, 1, "E. formation", text_size)
    }

    for k, ax in ax_dict.items():
        # Add static arrows
        if k in static_elements:
            for patch in static_elements[k]:
                # For ConnectionPatches, we need to set the transform correctly
                if isinstance(patch, ConnectionPatch):
                    patch.set_transform(ax.transData)
                ax.add_patch(patch)
            ax.set_axis_off()

        # Add static text
        if k in text_elements:
            x, y, s, size = text_elements[k]
            ax.text(x=x, y=y, s=s, size=size, horizontalalignment='center')
            ax.set_axis_off()

        # --- Plot data ---
        # Cumulative vars
        if k in ['H', 'N', 'T', 'E', 'C', 'O', 'D']:
            color = cmap(0.1)
            ax.text(0, 1, waterMark(k), transform=ax.transAxes, size=waterSize)
            plot_var = {'T': 'T_cum', 'C': 'SimpleC_cum', 'O': 'ExpNoise_cum', 'D': 'Disease_cum'}.get(k, k)
            onePlot(ax, dd=dd, plotVariable=plot_var, color=color, low_h_cut=low_h_cut, high_h_cut=high_h_cut, plotData=filteredData)
            if k == 'H' and 0 not in ax.get_yticks():
                ax.set_yticks(np.linspace(start=0, stop=ax.get_yticks().max(), num=8).round(1))

        # Dynamic vars
        if k in ['h', 't', 'b', 'e', 'o', 'd', 'c']:
            color = cmap(0.6)
            ax.text(0, 1, waterMark(k), transform=ax.transAxes, size=waterSize)
            plot_var = {'t': 'T', 'b': 'SimpleB', 'e': 'E_diff', 'o': 'ExpNoise', 'h': 'H_diff', 'd': 'Disease'}.get(k, k)
            onePlot(ax, dd=dd, plotVariable=plot_var, color=color, low_h_cut=low_h_cut, high_h_cut=high_h_cut, plotData=filteredData)

        # Subtitle
        if k == 's':
            decile_size = dd['H'].loc[(dd['H']['100'] <= high_h_cut) & (dd['H']['100'] >= low_h_cut)].shape[0]
            ax.set_title(f'Decile size = {decile_size} {sub_title}', fontsize=subtitleSize)
            ax.set_axis_off()
